services:
  - type: web
    name: dsa-notetaking-api
    env: node
    plan: starter
    buildCommand: cd backend-api && npm install && npm run build
    startCommand: cd backend-api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.vercel.app
    healthCheckPath: /health
    autoDeploy: true 